baseurl = "/"
languageCode = "en-us"
title = "Hidden Phoenix"
theme = "hugo-xmin"
googleAnalytics = "UA-121310852-2"
disqusShortname = "hiddenphoenix"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Trees, Treasures, and Tales From The Field: An Urban Forester's Blog"
    footer = "&copy; [Zach Wilder](https://github.com/zwilder) 2019 | [Github](https://github.com/zwilder)"
